site_name: buSP
repo_url: https://liviarodrigues1.github.io/App-buSP/

theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  palette:
    primary: red
    accent: indigo
  logo: assets/buSP.png
  features:
    - navigation.tabs

nav: 
  - Início: ./index.md
  - Apresentação: 
    - Apresentação: ./apresentacoes/apresentacao1.md
  - Planejamento: 
    - Metodologia: ./planejamento/metodologia.md
    - Ferramentas Utilizadas: ./planejamento/ferramentas.md
  - Elicitação:
    - Técnicas: 
      - Instrospecção: ./elicitacao/tecnicas/introspeccao.md
      - Observação: ./elicitacao/tecnicas/observacao.md
    - Personas: ./elicitacao/personas.md
  - Modelagem:
    - Casos de Uso: ./modelagem/casos_de_uso.md
    - Cenários: ./modelagem/cenarios.md
    - Especificação Suplementar: ./modelagem/especificacao_suplementar.md
    - NFR Framework: ./modelagem/nfrframework.md
    - Backlog:
      - Backlog do Produto: ./modelagem/backlog/product_backlog.md
      - Histórias de Usuário: ./modelagem/backlog/historias_de_usuario.md

markdown_extensions:
  - attr_list
  - md_in_html
